import os
import sys
import datetime

# Setup path so we can import from backend.app
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from backend.app.database import SessionLocal
from backend.app.models import Facility

db = SessionLocal()

new_facilities = [
    Facility(
        name="Koyambedu Bus Terminus Rest Area",
        category="REST_POINT",
        address="CMBT, Koyambedu, Chennai",
        zone="Koyambedu",
        city="Chennai",
        lat=13.0674,
        lng=80.1952,
        is_open=True,
        operating_hours="24 Hours Open",
        access_type="PUBLIC",
        pricing_info="Free to all workers",
        accessibility_info="Ground level, wide entryway",
        has_rest=True,
        has_washroom=True,
        has_water=True,
        has_charging=True,
        has_shade=True,
        has_parking=True,
        has_food=True,
        has_medical=False,
        verification_status="VERIFIED",
        verification_count=120,
        last_reported_at=datetime.datetime.utcnow() - datetime.timedelta(minutes=10),
        notes="Massive bus terminus with dedicated resting spots for gig workers. Plenty of food stalls and washrooms."
    ),
    Facility(
        name="OMR IT Expressway Rider Hub",
        category="SHADED_AREA",
        address="Rajiv Gandhi Salai, Thoraipakkam, Chennai",
        zone="Thoraipakkam",
        city="Chennai",
        lat=12.9696,
        lng=80.2443,
        is_open=True,
        operating_hours="06:00 - 23:00",
        access_type="PUBLIC",
        pricing_info="Free",
        accessibility_info="Along the service road",
        has_rest=True,
        has_washroom=False,
        has_water=True,
        has_charging=False,
        has_shade=True,
        has_parking=True,
        has_food=True,
        has_medical=False,
        verification_status="VERIFIED",
        verification_count=85,
        last_reported_at=datetime.datetime.utcnow() - datetime.timedelta(hours=1),
        notes="Shaded parking near IT parks. Popular waiting spot for food delivery riders."
    ),
    Facility(
        name="Mattuthavani Integrated Bus Stand Rest Zone",
        category="REST_POINT",
        address="M.G.R Bus Stand, Mattuthavani, Madurai",
        zone="Mattuthavani",
        city="Madurai",
        lat=9.9416,
        lng=78.1472,
        is_open=True,
        operating_hours="24 Hours Open",
        access_type="PUBLIC",
        pricing_info="Free corporation facility",
        accessibility_info="Ramp accessible",
        has_rest=True,
        has_washroom=True,
        has_water=True,
        has_charging=True,
        has_shade=True,
        has_parking=True,
        has_food=True,
        has_medical=True,
        verification_status="VERIFIED",
        verification_count=45,
        last_reported_at=datetime.datetime.utcnow() - datetime.timedelta(hours=2),
        notes="Spacious rest zone inside the bus stand. Clean drinking water and 24/7 food availability."
    ),
    Facility(
        name="Trichy Central Bus Stand EV & Rest Point",
        category="CHARGING",
        address="Cantonment, Tiruchirappalli",
        zone="Cantonment",
        city="Tiruchirappalli",
        lat=10.8050,
        lng=78.6856,
        is_open=True,
        operating_hours="05:00 - 23:30",
        access_type="PUBLIC",
        pricing_info="Free rest area, Standard EV rates",
        accessibility_info="Easily accessible from main road",
        has_rest=True,
        has_washroom=True,
        has_water=True,
        has_charging=True,
        has_shade=True,
        has_parking=True,
        has_food=True,
        has_medical=False,
        verification_status="VERIFIED",
        verification_count=60,
        last_reported_at=datetime.datetime.utcnow() - datetime.timedelta(minutes=45),
        notes="Ideal for cab drivers and EV riders. Washrooms available at the bus terminus nearby."
    ),
    Facility(
        name="Salem New Bus Stand Driver Oasis",
        category="REST_POINT",
        address="Meyyanur, Salem",
        zone="Meyyanur",
        city="Salem",
        lat=11.6669,
        lng=78.1362,
        is_open=True,
        operating_hours="24 Hours Open",
        access_type="PUBLIC",
        pricing_info="Free",
        accessibility_info="Ground level",
        has_rest=True,
        has_washroom=True,
        has_water=True,
        has_charging=False,
        has_shade=True,
        has_parking=True,
        has_food=True,
        has_medical=False,
        verification_status="VERIFIED",
        verification_count=35,
        last_reported_at=datetime.datetime.utcnow() - datetime.timedelta(hours=3),
        notes="Large resting area for drivers. Lots of shade and 24/7 tea stalls."
    ),
    Facility(
        name="Erode BS Washroom & RO Point",
        category="WASHROOM",
        address="Central Bus Stand, Erode",
        zone="Central",
        city="Erode",
        lat=11.3364,
        lng=77.7161,
        is_open=True,
        operating_hours="06:00 - 22:00",
        access_type="PUBLIC",
        pricing_info="Free",
        accessibility_info="Public facility",
        has_rest=False,
        has_washroom=True,
        has_water=True,
        has_charging=False,
        has_shade=True,
        has_parking=True,
        has_food=False,
        has_medical=False,
        verification_status="RECENTLY_REPORTED",
        verification_count=20,
        last_reported_at=datetime.datetime.utcnow() - datetime.timedelta(hours=1),
        notes="Clean drinking water and washroom facility. Suitable for quick stops."
    ),
    Facility(
        name="Tiruppur Old Bus Stand Food & Shade",
        category="FOOD",
        address="Old Bus Stand, Tiruppur",
        zone="Town Centre",
        city="Tiruppur",
        lat=11.1085,
        lng=77.3411,
        is_open=True,
        operating_hours="07:00 - 22:00",
        access_type="PUBLIC",
        pricing_info="Subsidized food",
        accessibility_info="Crowded area, limited large vehicle parking",
        has_rest=True,
        has_washroom=True,
        has_water=True,
        has_charging=True,
        has_shade=True,
        has_parking=True,
        has_food=True,
        has_medical=False,
        verification_status="VERIFIED",
        verification_count=50,
        last_reported_at=datetime.datetime.utcnow() - datetime.timedelta(minutes=30),
        notes="Very useful for inner-city delivery boys. Amma Unavagam and mobile charging spots available."
    ),
    Facility(
        name="Vannarpettai Junction Rest Area",
        category="REST_POINT",
        address="Vannarpettai, Tirunelveli",
        zone="Vannarpettai",
        city="Tirunelveli",
        lat=8.7188,
        lng=77.7471,
        is_open=True,
        operating_hours="05:00 - 23:00",
        access_type="PUBLIC",
        pricing_info="Free",
        accessibility_info="Tree shade along the highway",
        has_rest=True,
        has_washroom=False,
        has_water=True,
        has_charging=False,
        has_shade=True,
        has_parking=True,
        has_food=True,
        has_medical=True,
        verification_status="VERIFIED",
        verification_count=22,
        last_reported_at=datetime.datetime.utcnow() - datetime.timedelta(hours=4),
        notes="A great place to wait for rides. Cool breeze and plenty of tree shade."
    ),
    Facility(
        name="Kanyakumari Beach Road Waiting Spot",
        category="SHADED_AREA",
        address="Beach Road, Kanyakumari",
        zone="Beach",
        city="Kanyakumari",
        lat=8.0833,
        lng=77.5445,
        is_open=True,
        operating_hours="06:00 - 20:00",
        access_type="PUBLIC",
        pricing_info="Free",
        accessibility_info="Open public space",
        has_rest=True,
        has_washroom=True,
        has_water=True,
        has_charging=False,
        has_shade=True,
        has_parking=True,
        has_food=True,
        has_medical=False,
        verification_status="VERIFIED",
        verification_count=65,
        last_reported_at=datetime.datetime.utcnow() - datetime.timedelta(minutes=15),
        notes="Nice waiting area for auto and cab drivers. Public amenities are well maintained."
    ),
    Facility(
        name="Vellore Fort Roundana Rest & Medical Point",
        category="MEDICAL",
        address="Roundana, Vellore",
        zone="Fort Area",
        city="Vellore",
        lat=12.9350,
        lng=79.1350,
        is_open=True,
        operating_hours="24 Hours Open",
        access_type="PUBLIC",
        pricing_info="Free First-Aid",
        accessibility_info="Easy access from main road",
        has_rest=True,
        has_washroom=True,
        has_water=True,
        has_charging=True,
        has_shade=True,
        has_parking=True,
        has_food=False,
        has_medical=True,
        verification_status="VERIFIED",
        verification_count=28,
        last_reported_at=datetime.datetime.utcnow() - datetime.timedelta(hours=2),
        notes="Medical assistance available 24/7. First-aid, ORS available along with mobile charging stations."
    ),
    Facility(
        name="Thanjavur Old Bus Stand Rider Oasis",
        category="REST_POINT",
        address="Old Bus Stand, Thanjavur",
        zone="Old Town",
        city="Thanjavur",
        lat=10.7870,
        lng=79.1378,
        is_open=True,
        operating_hours="06:00 - 23:00",
        access_type="PUBLIC",
        pricing_info="Free",
        accessibility_info="Public area",
        has_rest=True,
        has_washroom=True,
        has_water=True,
        has_charging=True,
        has_shade=True,
        has_parking=True,
        has_food=True,
        has_medical=False,
        verification_status="RECENTLY_REPORTED",
        verification_count=15,
        last_reported_at=datetime.datetime.utcnow() - datetime.timedelta(minutes=55),
        notes="Historical town rest point for delivery agents. Shade, charging, and drinking water."
    ),
    Facility(
        name="Karur Bypass EV Swap Station",
        category="CHARGING",
        address="Bypass Road, Karur",
        zone="Bypass",
        city="Karur",
        lat=10.9601,
        lng=78.0766,
        is_open=True,
        operating_hours="24 Hours Open",
        access_type="PUBLIC",
        pricing_info="Standard EV swap rate",
        accessibility_info="Highway side",
        has_rest=False,
        has_washroom=True,
        has_water=True,
        has_charging=True,
        has_shade=True,
        has_parking=True,
        has_food=False,
        has_medical=False,
        verification_status="VERIFIED",
        verification_count=12,
        last_reported_at=datetime.datetime.utcnow() - datetime.timedelta(hours=5),
        notes="Quick EV swapping and charging station for gig vehicles. Cold water available."
    )
]

db.add_all(new_facilities)
db.commit()
print(f"Successfully injected {len(new_facilities)} facilities all over Tamil Nadu.")
db.close()
